name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # Executa diariamente às 18:00 UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3  # Baixa o conteúdo do repositório
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1  # Usa a ação para gerar o gráfico 3D
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação para o repositório
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
